- name: Change rights file /tmp/foo.conf
  hosts: all
  become: yes
  tasks:
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /tmp/foo.conf
        mode: '0600'
