---
- hosts: webservers
tasks:

- name: install remote rpm
yum:
name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
state: present

- name: install the zabbix-agent
yum:
name: zabbix-agent
state: present

- name: Enabling systemctl service and start
command: systemctl enable zabbix-agent

- name: Starting service
command: systemctl start zabbix-agent

- name: Allowing traffic to agent ports
command: firewall-cmd --zone=public --add-port=10050-10051/tcp --permanent

- name: Reloading
command: firewall-cmd --reload
